// Organization Actions
export const SET_ORGANIZATION = "SET_ORGANIZATION";
export const REQUEST_ORGANIZATION = "REQUEST_ORGANIZATION";
export const RECEIVE_ORGANIZATION = "RECEIVE_ORGANIZATION";

// Team Actions
export const REQUEST_TEAM_MEMBERS = "REQUEST_TEAM_MEMBERS";
export const RECEIVE_TEAM_MEMBERS = "RECEIVE_TEAM_MEMBERS";
